name: Build and Deploy

on:
  push:
    branches:
      - main # Der Workflow wird bei jedem Push in den main-Branch ausgelöst

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Verwendet die neueste LTS-Version von Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Commit and push the dist directory
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add dist/*
          git commit -m "Update dist directory from GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
