name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Der Workflow wird bei jedem Push in den main-Branch ausgelöst

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*' # Verwendet die neueste LTS-Version von Node.js

      - name: Install dependencies
        run: npm install

      - name: Build the app
        run: npm run build

      - name: Move built files to root
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          rsync -av --remove-source-files dist/ ./  # Kopiert den Inhalt und entfernt die Quell-Dateien
          rm -rf dist  # Löscht das dist-Verzeichnis, nachdem alles kopiert wurde
          git add .
          git commit -m "Deploy from GitHub Actions"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
